var translationsEN = {
        NAV_HOME: 'Home',
        NAV_HOTELS: 'Holtels & Resorts',
            NAV_NORTHTH: 'Northern Thailand',
            NAV_CENTRAL: 'Central & Eastern Regions',
            NAV_SOUTHEN: 'Southern Thailand',
        NAV_DINING: 'Find Dining',
        NAV_LIFTIME: 'One in A Lifetime',
        NAV_MADEINTH: 'Made in Thailand',
        NAV_WELLNESS: 'Wellness',
        NAV_LANG: 'Lang',

        INTRO_H : 'Introduction',
        INTRO_P1:'What is luxury? Is it a barefoot stroll across a reclaimed wood veranda to a private cove? A hot-air-balloon ride at sunrise to panoramic views of rolling vineyards? Or an exquisite Vintage Cuvée Champagne, paired with a beautifully executed progression of dinner courses? Perhaps a private jet to the most discreet of destination resorts?',
        INTRO_P2:'It is all these things, and yet luxury is also personal, inimitably so. It is the courage to turn from the usual to the unusual, from the conventional to the rarefied.',
        INTRO_P3:'With this in mind, explore the superlatives of Thailand’s luxury offerings, where private beaches, hot-air-balloons, Champagne and helicopter experiences (and much, much more) are not simply offered, but served to the utmost perfection, forever surpassing expectations.',

        HOME_BANGKOK_H : 'Bangkok City of Angels',

        HOME_BANGKOK_D1_P1 : 'Energising, charismatic and often as complex as ornate Thai script, Bangkok has as many different personalities as it does options for sumptuous food. ',
        HOME_BANGKOK_D1_P2 : 'There’s the hyper modern party animal; a place where days and evening spent in glitzy malls and restaurants graduate to risqué adult entertainment and pulsing nightclubs that keep bodies moving until dawn. ',
        HOME_BANGKOK_D1_P3 : 'Meanwhile, a mellower, more spiritual side, characterised by elaborate temples and palaces, canals and arty, alternative culture counterbalance these brasher aspects of the city. ',
        HOME_BANGKOK_D1_P4 : 'In Thailand all roads lead to Bangkok. The capital is the nation’s political centre, its spiritual and cultural hub, and a magnet for migrants from all over the country. Thais do a fine job of balancing the spiritual with the earthly. ',
        HOME_BANGKOK_D1_P5 : 'The Kingdom is 95 percent Buddhist, and Bangkok is blessed with hundreds of temples from humble pagodas to grand, gold-spired complexes. ',
        HOME_BANGKOK_D1_P6 : 'Just as strong as these religious beliefs is the Thai emphasis on sanuk, the idea that life should be fun. Although deadly serious when the occasion demands it, Thais tend to be very playful at work and in their day-to-day dealings ',
        HOME_BANGKOK_D1_P7 : 'Bangkok is widely known and admired for the contrasts it offers travellers. It is also catering increasingly adeptly to the well-heeled.  ',
        HOME_BANGKOK_D1_P8 : 'The roads in exclusive areas such as Thonglor and Ekkamai are clogged with the Ferraris and Lamborghinis of the Thai high society as they shuttle between new cutting-edge restaurants and clubs.',

        HOME_BANGKOK_D2_P1 : 'This proliferation of luxury is not confined to the traditional stomping grounds of the Thai elite either. From the commercial districts of Silom and Sukhumvit Road to the old city and the banks of the Chao Phraya River, luxury hotels, gastro-bars and other upscale haunts such as whisky and cigar bars and designer barbers are springing up with the regularity of a ticking metronome. ',
        HOME_BANGKOK_D2_P2 : 'From ultra-accomplished ventures by some of the world’s top chains to unique – and in many cases intricate – boutique boltholes, Bangkok’s selection of luxury hotels is one of Asia’s healthiest. Many of the big names are congregated in the commercial hubs of Sukhumvit and Silom. These areas are ideal for their proximity to the thick of the action, but many visitors prefer to be located near the Chao Phraya River for a more relaxed stay.',
        HOME_BANGKOK_D2_P3 : 'Although it remains (justifiably) most famous for its mind-blowing street food culture – something that unites both the haves and have-nots – Bangkok has emerged as an increasingly prestigious destination for upscale dining. In fact, according to the most recent list of the top 50 restaurants in Asia compiled by San Pellegrino, the continent’s top dining spot is currently Gaggan, where Calcutta-born chef Gaggan Anand flirts with molecular gastronomy to produce acclaimed Indian cuisine.',
        HOME_BANGKOK_D2_P4 : 'Bangkok’s reputation as a nightlife playground is richly deserved. Nevertheless, there’s more refinement and subtlety to the scene than lurid tales of neon-lit fleshpots would have you believe.',

        HOME_BANGKOK_D3_P1 : 'Although it was a small trading post as recently as the 15th century, Bangkok has been at the heart of Thailand’s modernisation. The city, therefore, is littered with important landmarks, both regal and spiritual. The iconic sights are mostly concentrated near the Chao Phraya River where you will find the Grand Palace and Dusit Palace as well as famous temples such as Wat Pho, home to the world’s largest reclining Buddha, and Wat Phra Kaew, the most sacred temple in Thailand.',
        HOME_BANGKOK_D3_P2 : 'Muay Thai (Thai boxing) may be the country’s national sport, but shopping is undoubtedly Thailand’s national pastime. For variety and value, Bangkok is far and away the best retail experience in Southeast Asia. Sleek megamalls boast high-end designers, international brands and a smattering of breakthrough Thai labels. For local character, meanwhile, Chatuchak Weekend Market and Talat Rot Fai offer thousands of stalls and just as many opportunities to empty your wallet.',
        HOME_BANGKOK_D3_P3 : 'Although famously fast-paced, there’s a gentler, more relaxed side to the city. Leafy neighbourhoods such as Banglamphu and Ari shelter arty cafés and hip music venues while a boat on the Chao Phraya River is a fine vantage point from which to observe the city in all its glory. In fact, few Bangkok experiences are more inspiring than witnessing one of the city’s legendary sunsets from a river boat or from one of the many classy venues that continue to sprout up along the banks of the royal waterway. ',
        HOME_BANGKOK_D3_P4 : 'It is hot, frenetic, and sometimes overwhelming, but one thing the Thai capital can never pretend to be is boring. ',

        
        HOME_NORTHERN_H : 'Northern Thailand Lanna Charms',

        HOME_NORTHERN_D1_P1 : 'In a country of high-profile tourist attractions and destinations, northern Thailand is sometimes neglected. Yet while paradisiacal beaches and sumptuous coastal resorts might be absent, this part of the Kingdom is as rich in luxury appeal as any. ',
        HOME_NORTHERN_D1_P2 : 'Most visitors base themselves in Chiang Mai – Thailand’s cultural capital and second-most populous city after Bangkok. The city’s appealing situation in the cradle of emerald mountains and its easy balance of tradition and modernity make it a fine place to strike out from.',
        HOME_NORTHERN_D1_P3 : 'However, the region has plenty more strings to its bow. Forested mountains, vibrant rice paddies and rushing rivers imbue it with a bucolic, almost Edenic feel while towns and villages such as Pai, Mae Hong Son and Chiang Rai abound with hill-tribe culture and easy-going, laidback vibes.',
        HOME_NORTHERN_D1_P4 : 'For the vast majority of visitors, Chiang Mai is the perfect gateway from which to explore northern Thailand. Although it is Thailand’s second city, Chiang Mai couldn’t be further removed from Bangkok. Nestled in the foothills of northern Thailand, the city is replete with hundreds of sacred temples, many of which date back to its days as the capital of the ancient Kingdom of Lanna.',
        HOME_NORTHERN_D1_P5 : 'These holy relics, as well as the city’s quaint moated old quarter and its location amidst prime visual splendour, make Chiang Mai a special place to be.',
        HOME_NORTHERN_D1_P6 : 'These holy relics, as well as the city’s quaint moated old quarter and its location amidst prime visual splendour, make Chiang Mai a special place to be.',

        HOME_NORTHERN_D2_P1 : 'Away from the historic centre, it is very much a dynamic and modern place. Areas such as Nimmanhaemin thrum with creative energy as the movers and shakers of the city carve out contemporary art and music venues amid the concrete shophouses.',
        HOME_NORTHERN_D2_P2 : 'Leisure options also abound. Some of the Kingdom’s finest golf courses are located near the city. Meanwhile, activities such as rock climbing and zip-lining bolster Chiang Mai’s claim to be one of Thailand’s preeminent bases for adventure activities.',
        HOME_NORTHERN_D2_P3 : 'Yet, despite its contemporary trappings, Chiang Mai remains a sanctuary. Its magical qualities hit a spellbinding zenith in the range of ultra-deluxe accommodations on offer. From sumptuous boutique hideaways that evoke the old-world elegance of the Orient to extravagant resorts that incorporate picturesque rice paddies, tropical hardwoods and traditional Lanna architecture, the city and its environs boast some of Thailand’s most affecting retreats.',
        HOME_NORTHERN_D2_P4 : 'Leisure options also abound. Some of the Kingdom’s finest golf courses are located near the city. Meanwhile, activities such as rock climbing and zip-lining bolster Chiang Mai’s claim to be one of Thailand’s preeminent bases for adventure activities.',
        HOME_NORTHERN_D2_P5 : 'Yet, despite its contemporary trappings, Chiang Mai remains a sanctuary. Its magical qualities hit a spellbinding zenith in the range of ultra-deluxe accommodations on offer. From sumptuous boutique hideaways that evoke the old-world elegance of the Orient to extravagant resorts that incorporate picturesque rice paddies, tropical hardwoods and traditional Lanna architecture, the city and its environs boast some of Thailand’s most affecting retreats. ',

        HOME_NORTHERN_D3_P1 : 'Despite Chiang Mai’s centrality, the north of Thailand is far from a one-city show. The first true Thai kingdoms rose in this part of the country, and northerners are fiercely proud of their local customs and heritage. The north is also home to most of the country’s ethnic tribes, with Karen, Shan and Yunnanese among those who have made their homes in remote mountain valleys.',
        HOME_NORTHERN_D3_P2 : 'first true Thai kingdoms rose in this part of the country, and northerners are fiercely proud of their local customs and heritage. The north is also home to most of the country’s ethnic tribes, with Karen, Shan and Yunnanese among those who have made their homes in remote mountain valleys.',
        HOME_NORTHERN_D3_P3 : 'Significantly smaller than Chiang Mai, yet still blessed with alluring restaurants and hotels along with a wide range of activities and leisure options, Chiang Rai is winning favour as an alternative base in the region. Thailand’s northern-most city, Chiang Rai is located in the famous Golden Triangle, the confluence of Thailand, Laos and Myanmar. An area of remarkable physical beauty, this part of Thailand also offers visitors the opportunity to partake in a wealth of unforgettable outdoor activities with trips to superbly run elephant camps among the many highlights.',
        HOME_NORTHERN_D3_P4 : 'Whether it is Chiang Mai, Chiang Rai or one of its lesser-known provinces, Thailand’s uppermost reaches offer endless possibilities.',

 
        HOME_PHUKET_H : 'Phuket The Pearl of the Andaman',

        HOME_PHUKET_D1_P1 : 'Thailand’s biggest island, Phuket is long established as one of the jewels in the Kingdom’s tourism crown. Famed the world over for its white-sand beaches, fabulous resorts and buzzing nightlife, the destination remains as attractive as ever to those seeking a healthy dose of pure indulgence.',
        HOME_PHUKET_D1_P2 : 'One of the most precious things about the island is its endlessly multi-faceted character. Yes, there are resorts and beaches to die for, but this is far more than a mere holiday paradise; it is a living and breathing island with its own history, character and traditions.',
        HOME_PHUKET_D1_P3 : 'Phuket’s strategic location has attracted traders from around the globe and the island has absorbed influences from Europe, Arabia and China. These cultural quirks may not be immediately apparent to those who choose to sequester themselves in their resort. However, the island’s rich melange of shaping factors asserts itself in everything from its strong Muslim heritage to its distinctive architecture and acclaimed cuisine.',
        HOME_PHUKET_D1_P4 : 'A large portion of what makes Phuket so distinct can be attributed to its sheer size. Although surrounded by the Andaman Sea on all sides, the island’s healthy dimensions mean that it is often hard to believe that you are cut off from the mainland. Yet, while this accessibility brings with it multi-lane highways and other big city attributes such as shopping malls, the extra space means that it is easy enough to find respite from the crowds wherever you are.',
        HOME_PHUKET_D1_P5 : 'For those in search of a lively kind of vacation, Phuket’s more commercial beaches are equipped with everything from classy restaurants to stunning beach clubs. Of these options, Patong, Kata and Karon are the most famous and all are blessed with plentiful luxurious resorts and other facilities. Away from the more commercial areas, the island boasts several quieter – yet still very well-serviced – enclaves such as Surin, Rawai and Kamala beaches. Elsewhere, Phuket has several of the country’s best resorts, many with their own spotlessly white private beach sloping gently down towards the crystalline water of the Andaman Sea.',

        HOME_PHUKET_D2_P1 : 'Less famous than the main island but often equally attractive are the islands that pepper the ocean near Phuket. Located in stunning Phang Nga Bay, the twin islands of Koh Yao Yai and Koh Yao Noi are two of Thailand’s most underrated with some fantastic beaches and resorts as well as a laidback and friendly Muslim culture.',
        HOME_PHUKET_D2_P2 : 'As Thailand’s most popular holiday island it is no surprise that Phuket is particularly blessed with first-class golf courses. Red Mountain Club, The Lakes course at Blue Canyon and Phuket Country Club have garnered plaudits both for the standard of golf and the stunning scenery on offer, and quality is equally high elsewhere on the island.',
        HOME_PHUKET_D2_P3 : 'Diving is another undoubted highlight of a visit to Phuket. Day trips from Phuket to diving hotspots such as Phi Phi and the Racha Islands operate throughout the year. A little further afield, but certainly worth making the extra effort for, are the world-class scuba sites at the Similan and Surin Islands in the Andaman Sea.',
        HOME_PHUKET_D2_P4 : 'Located a reasonable distance from Phuket off the shores of Phang Nga Province, these pristine outcrops are best experienced via a liveaboard dive cruise. Guests don’t have to venture too far from Phuket itself to experience the wonders of the Andaman Sea. Activities such as stand-up paddle-boarding, windsurfing and kayaking are growing in popularity while Phuket is famously home to the King’s Cup Regatta, Thailand’s most prestigious sailing event.',
        HOME_PHUKET_D2_P5 : 'As you might expect from a destination so experienced at catering to the needs of a global visitor base, one of Phuket’s specialties is its culinary scene. Here you’ll find everything from classic and contemporary fine dining to some of Thailand’s most delicious seafood restaurants. Special mention must be made of the dining scene in Phuket Town. The island’s capital is not the most obvious tourist destination, but it is well worth visiting for its unique – often Chinese-influenced – cuisine. ',

        HOME_PHUKET_D3_P1 : 'Indeed, the dining scene in Phuket Town is indicative of a different – less commercial – side to Phuket that is often overlooked by visitors.  Known as the “Pearl of the Andaman”, the island’s beautiful interior shelters gibbon rehabilitation projects as well as fruit orchards, towering waterfalls and rubber tree plantations.',
        HOME_PHUKET_D3_P2 : 'Phuket Town, meanwhile, is one of Thailand’s most compelling provincial towns with a beguiling blend of cultural influences. Other highlights for visitors include zip-lining, cooking schools and colourful Chinese temples.',
        HOME_PHUKET_D3_P3 : 'For the majority of visitors, however, it is Phuket’s dazzling beaches and crystalline waters that earn top billing.  As the daylight hours fade and the sun sinks towards the Andaman Sea, many visitors head towards Promthep Cape in the island’s south to catch the last rays of the day. Alternatively, the island’s many stunning beach bars are the perfect place to propose a toast to the end of another day in paradise.',
}